proyek/akun/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns =[
    path('',views.LoginView, name='logi_view'),
    path('register/',views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('daftarakun/', views.DaftarAkun.as_view(), name='daftar_akun'),
    path('jurnal/', views.Jurnal.as_view(), name='jurnal'),
    path('bukubesar/', views.BukuBesar.as_view(), name='buku_besar'),
    path('jurnal/delete/', views.JurnalDelete.as_view(), name='jurnal_delete'),
    path('jurnal/edit/<int:pk>/',views.JurnalEdit.as_view(),name='jurnal_edit'),
    path('labarugi/', views.LabaRugiView.as_view(), name='laba_rugi'),
    path('neraca/', views.NeracaView.as_view(), name='neraca'),
    path('daftarakun/delete/', views.AkunDelete.as_view(), name='akun_delete'),
    path('daftarakun/eidt/<int:pk>/', views.AkunEdit.as_view(), name='akun_edit'),
    path('reset/', views.reset_filter, name='reset_filter'),
    path('beranda/', views.Dashboard.as_view(), name='beranda')
]

proyek/proyek/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('akun.urls'))
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

proyek/templates/includes/akun_edit.html
<style>
    .inputan{
        background-color: transparent;
    }
</style>
<div class="payments">
    <h3 class="title">Form Edit</h3>
    <form action="" method="post" class="inputan">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit">Update</button>
    </form>
</div>

proyek/templates/includes/beranda.html
<div class="cards">
    <img src="{{ chart }}" alt="total pendapatan" class="chart">
    <img src="{{ chart }}" alt="total pendapatan" class="chart">
</div>

proyek/templates/includes/cards.html
<div class="cards">
    <div class="card satu">
        <div class="box">
            <h1>50</h1>
            <h3></h3>
        </div>
        <div class="icon">
            <i class="fas fa-money-bill-alt"></i>         
        </div>
    </div>
    <div class="card dua">
        <div class="box">
            <h1>50</h1>
            <h3></h3>
        </div>
        <div class="icon">
            <i class="fas fa-cog"></i>        
        </div>
    </div>
    <div class="card tiga">
        <div class="box">
            <h1>50</h1>
            <h3></h3>
        </div>
        <div class="icon">
            <i class="fas fa-hands-helping"></i>         
        </div>
    </div>
    <div class="card empat">
        <div class="box">
            <h1>50</h1>
            <h3></h3>
        </div>
        <div class="icon">
            <i class="fa-solid fa-hand-holding-dollar"></i>         
        </div>
    </div>
</div>

proyek/templates/includes/form.html
<div class="form">
    <form action="" method="post" class="inputan">
        <div class="nav-login">
            <h3>{% if request.path == '/register/' %} Form pendaftaran {% else %} Form login {% endif %}</h3>
            <ul class="ul-form-login">
                <li>
                    <a href="{% url 'user:register' %}">Daftar</a>
                </li>
                <li>
                    <a href="{% url 'user:logi_view' %}">Login</a>
                </li>
            </ul> 
        </div>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form> 
</div>

proyek/templates/includes/header.html
<div class="header">
    <div class="nav">
        <div class="search">
            <input type="text" name="" id="" placeholder="pencarian...">
            <button type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
        </div>
        <div class="user">
            <a href="" class="btn"><i class="fa-solid fa-plus"></i></a>
            <a href="#" class="btn"><i class="fa-regular fa-bell"></i></a>
            <a href="#" class="btn"><i class="fa-solid fa-user-tie"></i></a>
        </div>
    </div>
</div>

proyek/templates/includes/jurnal_edit.html
<style>
    .inputan{
        background-color: transparent;
    }
</style>
<div class="payments">
    <h3 class="title">Form Edit</h3>
    <form action="" method="post" class="inputan">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit">Update</button>
    </form>
</div>

proyek/templates/includes/labarugi.html
{% load humanize %}
<div class="payments">
    <div class="title">
        <h3>Laba Rugi</h3>
        <div class="ikon">
            <button onabort="printPDF()" class="pdf">
                <i class="fas fa-file-pdf"></i>
            </button>
            <i class="fas fa-file-excel"></i>
        </div>
    </div>
    <table>
        <thead>
            <tr class="title-table">
                <th>Akun</th>
                <th>Balance</th>
            </tr>
        </thead>
        <tbody>
            <!-- Pendapatan -->
            {% for akun, data in ledgers_pendapatan.items %}
            <tr>
                <td>{{ akun }}</td>
                <td>Rp.{{ data.balance |intcomma }}</td>
            </tr>
            {% endfor %}
            <tr class="title-table">
                <td>Total Pendapatan</td>
                <td>Rp.{{ total_pendapatan|intcomma }}</td>
            </tr>
        
            <!-- Beban -->
            {% for akun, data in ledgers_beban.items %}
            <tr>
                <td>{{ akun }}</td>
                <td>Rp.{{ data.balance|intcomma }}</td>
            </tr>
            {% endfor %}
            <tr class="title-table">
                <td>Total Beban</td>
                <td>Rp.{{ total_beban|intcomma }}</td>
            </tr>
        
            <!-- Laba Rugi -->
            <tr class="title-table">
                <td>Laba Rugi</td>
                <td>Rp.{{ laba_rugi|intcomma }}</td>
            </tr>
        </tbody>
        
    </table>
</div>

proyek/templates/includes/neraca.html
{% load humanize %}
<div class="payments">
    <div class="title">
        <h3>Neraca</h3>
        <div class="ikon">
            <button onabort="printPDF()" class="pdf">
                <i class="fas fa-file-pdf"></i>
            </button>
            <i class="fas fa-file-excel"></i>
        </div>
    </div>
    <table>
        <thead>
            <tr class="title-table">
                <th>Akun</th>
                <th>Balance</th>
            </tr>
        </thead>
        <tbody>
            <!-- Pendapatan -->
            {% for akun, data in ledgers_aktiva.items %}
            <tr>
                <td>{{ akun }}</td>
                <td>Rp.{{ data.balance |intcomma }}</td>
            </tr>
            {% endfor %}
            <tr class="title-table">
                <td>Total Aktiva</td>
                <td>Rp.{{ total_aktiva|intcomma }}</td>
            </tr>
        
            <!-- Beban -->
            {% for akun, data in ledgers_passiva.items %}
            <tr>
                <td>{{ akun }}</td>
                <td>Rp.{{ data.balance|intcomma }}</td>
            </tr>
            {% endfor %}
            
            <!-- Laba Rugi -->
            <tr>
                <td>Laba Ditahan</td>
                <td>Rp.{{ neraca|intcomma }}</td>
            </tr>

            <tr class="title-table">
                <td>Total Passiva</td>
                <td>Rp.{{ total_aktiva|intcomma }}</td>
            </tr>
        </tbody>
        
    </table>
</div>

proyek/templates/includes/payment_bb.html
{% load humanize %}
<div class="payments">
    <button class="pdf" onclick="printPDF()"><i class="fas fa-file-pdf"></i></button>
    
    {% for account_name, ledger in ledgers.items %}
    <h3 class="title">{{account_name}}</h3>
    <table>
        <thead>
            <tr class="title-table">
                <th>No</th>
                <th>Uraian</th>
                <th>Debit</th>
                <th>Kredit</th>
                <th>Saldo</th>
            </tr>
        </thead>
        <tbody>
            {% with 1 as counter %}
            {% for transaction in ledger.transactions %}
                <tr>
                    <td>{{forloop.parentloop.counter}}.{{forloop.counter}}</td>
                    <td>{{ transaction.uraian }}</td>
                    <td>{{ transaction.debit|intcomma }}</td>
                    <td>{{ transaction.kredit|intcomma }}</td>
                    <td>{{ transaction.balance|intcomma }}</td>
                </tr>
            {% endfor %}
            {% endwith %}
            {% if not ledger.transactions %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td colspan="4">Tidak ada transaksi</td>
            </tr>
            {% endif %}
            <tr class="title-table">
                <td><strong>Total</strong></td>
                <td><strong></strong></td>
                <td><strong>{{ ledger.total_debit|intcomma }}</strong></td>
                <td><strong>{{ ledger.total_kredit|intcomma }}</strong></td>
                <td><strong>{{ ledger.balance|intcomma }}</strong></td>
            </tr>
        </tbody>
    </table>
    {% endfor %}
</div>

proyek/templates/includes/payments.html
{% load static %}
{% load humanize %}
<div class="payments">
    <div class="title">
        <form action="{% url 'user:jurnal' %}" method="get">
            <input type="date" name="tanggal" id="">
            <input type="number" name="bulan" id="" min="1" max="12" placeholder="Bulan">
            <input type="number" name="tahun" id="" min="2000" max="2099" placeholder="Tahun">
            <button type="submit">Filter</button>
        </form>
        <form action="{% url 'user:reset_filter' %}" method="get">
            <button type="submit">Reset</button>
        </form>
        <h3>{{ total_debit| intcomma }}</h3>
        <h3>{{ total_kredit | intcomma }}</h3>
        <h3>{{ balance|intcomma }}</h3>
        {% if balance != 0 %}
        <p style="color: red;">Tidak Balance</p>
        {% else %}
        <p style="color: limegreen;">Balance</p>
        {% endif %}
        <div class="btn">
            <i class="fa-solid fa-plus" id="jurnal"></i>
        </div>
    </div>
    <table>
        <tr class="title-table">
            <th>No</th>
            <th>Tanggal</th>
            <th>Uraian</th>
            <th>Akun</th>
            <th>Debit</th>
            <th>Kredit</th>
            <th colspan="2">Action</th>
        </tr>
        {% for jurnal in jurnal_list %}
        <tr class="{% if forloop.counter|divisibleby:2 %} even {% else %} odd {% endif %}">
            <td>{{ forloop.counter }}</td>
            <td>{{ jurnal.tanggal }}</td>
            <td>{{ jurnal.uraian }}</td>
            <td>{{jurnal.akun.nama_akun}}</td>
            <td>{{jurnal.debit|intcomma}}</td>
            <td>{{jurnal.kredit|intcomma}}</td>
            <td>
                <form method="post" action="{% url 'user:jurnal_delete' %}">
                    {% csrf_token %}
                    <input type="hidden" name="jurnal_id" value="{{ jurnal.id }}">
                    <button type="submit"><i class="fas fa-trash"></i></button>
                </form>                
            </td>
            <td>
                <a href="{% url 'user:jurnal_edit' jurnal.id %}"><i class="fas fa-edit"></i></a>
            </td>
        </tr>
        {% endfor %}
    </table>
            
    <div class="dialog-jurnal">
        <h4 id="close-jurnal">Close</h4>
        <form action="{% url 'user:jurnal' %}" method="post" class="inputan">
            {% csrf_token %}
            <select name="akun" id="akun">
                {% for profil in profil_list %}
                    <option value="{{ profil.id }}">{{ profil.nama_akun }}</option>
                {% endfor %}
            </select>
            <input type="date" name="tanggal" id="">
            <input type="text" name="uraian" id="" placeholder="Uraian">
            <input type="number" name="debit" id="" placeholder="Debit">
            <input type="number" name="kredit" id="" placeholder="Kredit">
            <button type="submit">Save</button>
        </form>
    </div>        
</div>

proyek/templates/includes/poster.html
{% load static %}
<div class="poster">
    <img src="{% static 'gmb/akuntansi.png' %}" alt="">
</div>        

proyek/templates/includes/sidebar.html
<div class="sidebar">
    <div class="brand">
        <i class="fa-solid fa-qrcode"></i>&nbsp;&nbsp;
        <h1>{{user.username}}</h1>
    </div>
    <ul>
        <li><i class="fa-solid fa-gauge"></i>&nbsp;&nbsp;</fa-gauge><span><a href="{% url 'user:beranda' %}">Dashboard</a></span></li>
        <li><i class="fas fa-hands-helping"></i>&nbsp;&nbsp;<span><a href="{% url 'user:daftar_akun' %}">Daftar Akun</a></span></li>
        <li><i class="fa-solid fa-hand-holding-dollar"></i>&nbsp;&nbsp;<span><a href="{% url 'user:jurnal' %}">Jurnal Umum</a></span></li>
        <li><i class="fa-regular fa-circle-question"></i>&nbsp;&nbsp;<span><a href="{% url 'user:buku_besar' %}">Buku Besar</a></span></li>
        <li><i class="fa-solid fa-gear"></i>&nbsp;&nbsp;<span><a href="{% url 'user:laba_rugi' %}">Laba Rugi</a></span></li>
        <li><i class="fas fa-sign-out-alt"></i>&nbsp;&nbsp;<span><a href="{% url 'user:neraca' %}">Neraca</a></span></li>
        <li><i class="fas fa-sign-out-alt"></i>&nbsp;&nbsp;<span><a href="{% url 'user:logout' %}">Logout</a></span></li>
    </ul>
</div>

proyek/templates/includes/students.html
<div class="payments">
    <div class="students">
        <div class="title">
            <h2>Daftar Akun</h2>
            <div class="btn">
                <i class="fa-solid fa-plus" id="profil"></i>
            </div>
        </div>
        <table>
            <tr class="title-table">
                <th>No</th>
                <th>Nomor</th>
                <th>Nama Akun</th>
                <th>Pos</th>
                <th>Master Akun</th>
                <th>Saldo Normal</th>
                <th colspan="2">Action</th>
            </tr>
            {% for item in profil_list %}
            <tr class="{% if forloop.counter|divisibleby:2 %} even {% else %} odd {% endif %}">
                <td>{{ forloop.counter }}</td>
                <td>{{ item.nomor }}</td>
                <td>{{ item.nama_akun }}</td>
                <td>{{ item.pos }}</td>
                <td>{{ item.master_akun }}</td>
                <td>{{ item.saldo_normal }}</td>
                <td>
                    <form action="{% url 'user:akun_delete' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="akun_id" value="{{ item.id }}">
                        <button type="submit"><i class="fas fa-trash"></i></button>
                    </form>
                </td>
                <td><a href="{% url 'user:akun_edit' item.id %}"><i class="fas fa-edit"></i></a></td>
            </tr>
            {% endfor %}
        </table>
        <div class="dialog-form">
            <h4 id="close-akun">Close</h4>
            <form action="{% url 'user:daftar_akun' %}" method="post" class="inputan">
                {% csrf_token %}
                <input type="text" name="nama_akun" id="" placeholder="Nama Akun">
                <input type="text" name="nomor" id="" placeholder="Nomor Akun">
                <select name="pos" id="pos">
                    {% for choice in pos_choices %}
                    <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                    {% endfor %}
                </select>
                <select name="master_akun" id="master_akun">
                    {% for choice in master_choices %}
                    <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                    {% endfor %}
                </select>
                <select name="saldo_normal" id="sn_choices">
                    {% for choice in sn_choices %}
                    <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                    {% endfor %}
                </select>
                
                <button type="submit">Save</button>
            </form>
        </div>    
    </div>
</div>